# Generated by Django 5.0.6 on 2024-06-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
