# Generated by Django 5.0.6 on 2024-06-26 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_second_name_account_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pin',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
