# Generated by Django 5.0.6 on 2024-07-02 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MaxLengthValidator(11), django.core.validators.MinLengthValidator(11)]),
        ),
    ]
